language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: X08uZwiZmiyyBFfdQgZeLhc0xssGb+npItKs+OR49trJ8pYxXMUs57+AN4bs9htLKvjg7y764tFbYsW+1oLux50chuqGJ85knUAS6nPEprZLFWBM0uhRGUEkoiTJxreY61mZpME1WXXBcM/sBD8vqadQizl6ivwwSwLRQHSHgjU=
  - secure: bIEGy4VwEuCU/1FF/5OYc1KnsZqDx+Zwlsc/0yylw1gSeQGnhXpEQd8ul1lMLf8g9ebSXHpuA9xUn4JvfVMfRikyzoUuXiIDG1mdoBtlUFsuB4le8hapVHR+AXUCg4x/BwqNtkgBNOYXJpTDNx5XlafMsU3bGW5JPelTYp6sFJU=
